export enum LocalStorageKeys {
  RECAPTCHA_TOKEN = 'RECAPTCHA_TOKEN',
  AUTH_STORE = 'AUTH_STORE',
  DID_SEEN_PRE_RECEIPT_TOOLTIP = 'DID_SEEN_PRE_RECEIPT_TOOLTIP',
  DID_SEEN_IN_TRANSIT_TOOLTIP = 'DID_SEEN_IN_TRANSIT_TOOLTIP',
  DID_SEEN_TRANSFER_TUTORIAL = 'DID_SEEN_TRANSFER_TUTORIAL',
  DID_SEEN_RECEIVE_PRODUCT_TUTORIAL = 'DID_SEEN_RECEIVE_PRODUCT_TUTORIAL',
  DID_SEEN_DEFECT_ARRIVAL_ALERT = 'DID_SEEN_DEFECT_ARRIVAL_ALERT',
  DID_SEEN_MACHINE_TOOLTIP_IN_OM = 'DID_SEEN_MACHINE_TOOLTIP_IN_OM',
  DEFECT_ON_ARRIVAL_INITIATED_MOVEMENT_ORDER_IDS = 'DEFECT_ON_ARRIVAL_INITIATED_MOVEMENT_ORDER_IDS',
}
